apiVersion: v1
kind: Service
metadata:
  name: korrk-argocd
  namespace: argocd
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30003
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  type: NodePort