apiVersion: v1
kind: Service
metadata:
  name: korrk-postgre
  namespace: korrk-prod
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
    nodePort: 30002
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: korrk-postgresql
    app.kubernetes.io/name: postgresql
  type: NodePort